### ISSUE TITLE
Searching for contacts emails only

### ISSUE THREAD

**Issue by JailbirdInteractive** [quiin/UnifiedContactPicker#1]
Hey, is there any way to only search for contacts' email addresses? Also, is the search bar in the preview gif a part of the library? Thanks

**Comment by quiin** [comment]
Hi there, here's an example of how you can display only those contacts with one or multiple emails.

```java
public void launchContactPicker(View view) {
        int permissionCheck = ContextCompat.checkSelfPermission(this, Manifest.permission.READ_CONTACTS);
        if(permissionCheck == PackageManager.PERMISSION_GRANTED){
            Intent contactPicker = new Intent(this, ContactPickerActivity.class);
            String customSelection = "(" + ContactsContract.Data.MIMETYPE + "=? )";
            String [] customArgs = new String [] {ContactsContract.CommonDataKinds.Email.CONTENT_ITEM_TYPE};
            contactPicker.putExtra(ContactPickerActivity.CP_EXTRA_SELECTION,customSelection);
            contactPicker.putExtra(ContactPickerActivity.CP_EXTRA_SELECTION_ARGS, customArgs);
            contactPicker.putExtra(ContactPickerActivity.CP_EXTRA_HAS_CUSTOM_SELECTION_ARGS, true);
            startActivityForResult(contactPicker, CONTACT_PICKER_REQUEST);
        }else{
            ActivityCompat.requestPermissions(this,
                    new String[] {Manifest.permission.READ_CONTACTS},
                    READ_CONTACT_REQUEST);
        }
    }
```

What this does is basically query only those contacts with known communication MIME type that matches an email MIME type. If you require more information about contact querying, I suggest you take a look [here](https://developer.android.com/training/contacts-provider/retrieve-names.html)

Now. Regarding the search bar, It is part of this library and it actually is the _Chip View_  So if you are not able to see it. Please make sure you are not setting the following extra option:

```java
// This option is to show or not the chip view (this view includes the search icon & functionality)
contactPicker.putExtra(ContactPickerActivity.CP_EXTRA_SHOW_CHIPS, false);
```

I am aware that it may be usefull for some people to hide the chips but still be able to search within the queried contacts. I'll be adding this functionality in a further realease.

Hope this helps!

**Comment by JailbirdInteractive** [comment]
Thanks alot. This is super useful.
