### ISSUE TITLE
Hiding the actionbar

### ISSUE THREAD

**Issue by jcrooke** [quiin/UnifiedContactPicker#2]
Is there a way to hide the action bar on the `ContactPickerActivity` - I've tried setting this in my manifest file but to no avail;

```
<activity android:name="mx.com.quiin.contactpicker.ui.ContactPickerActivity"
            android:theme="@style/AppTheme.NoActionBar">
</activity>
```

**Comment by quiin** [comment]
This feature is not available at the moment. I'll gladly add it to the next release version (I can't guaranty a specific date but expect it before February finishes)

Feel free to issue a pull request if you come to a solution anytime before next release.

I'll leave this issue open until next release or pull request.

**Comment by adarshvijayanp** [comment]
@quiin 

Did you resolve this issue?
